server:
  port: 7865

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.12:8763/eureka/

spring:
  application:
    name: cloudoer-gateway
  redis:
    host: 192.168.1.12
    port: 6378
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: cloudoer-cl-common
        uri: lb://cloudoer-cl-common
        predicates:
        - Path=/common/**
        filters:
        - StripPrefix=1

      - id: cloudoer-cl-community
        uri: lb://cloudoer-cl-community
        predicates:
          - Path=/community/**
        filters:
          - StripPrefix=1

      - id: cloudoer-cl-mall
        uri: lb://cloudoer-cl-mall
        predicates:
          - Path=/mall/**
        filters:
          - StripPrefix=1

      - id: cloudoer-cl-uaaa
        uri: lb://cloudoer-cl-uaaa
        predicates:
          - Path=/uaaa/**
        filters:
          - StripPrefix=1
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 10
              redis-rate-limiter.burstCapacity: 20
              key-resolver: "#{@ipKeyResolver}"