server:
  port: 7001

spring:
  application:
    name: byx-gateway
  redis:
    host: 192.168.2.200
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.200:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: lk-comm
        uri: lb://lk-comm
        predicates:
        - Path=/comm/**
        filters:
        - StripPrefix=1

      - id: lk-rbac
        uri: lb://lk-rbac
        predicates:
          - Path=/rbac/**
        filters:
          - StripPrefix=1

      - id: lk-mall
        uri: lb://lk-mall
        predicates:
          - Path=/mall/**
        filters:
          - StripPrefix=1

      - id: lk-mgt
        uri: lb://lk-mgt
        predicates:
          - Path=/mgt/**
        filters:
          - StripPrefix=1
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 10
              redis-rate-limiter.burstCapacity: 20
              key-resolver: "#{@ipKeyResolver}"

jwt:
  secret: my-secret